import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ClientAuth from '@/components/auth/ClientAuth'
import ClientToaster from '@/components/auth/ClientToaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Inicia sesión | LifeQuiro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientAuth />
        {children}
        <ClientToaster />
      </body>
    </html>
  )
}