import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ClientToaster from '@/components/auth/ClientToaster'
import ClientAuth from '@/components/auth/ClientAuth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Inicia sesión | LifeQuiro',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico'
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.5.2/css/all.css" />
      </head>
      <body className={inter.className}>
        <ClientAuth />
        {children}
        <ClientToaster />
      </body>
    </html>
  )
}